kind = "web"
previewPath = "/"
title = "Tu Bingazo"
version = "1.0.0"
id = "artifacts/tu-bingazo"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24958

[services.development]
run = "pnpm --filter @workspace/tu-bingazo run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/tu-bingazo", "run", "build" ]
publicDir = "artifacts/tu-bingazo/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24958"
BASE_PATH = "/"
